services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    expose:
      - 14250
    ports:
      - 4317:4317 
      - 16686:16686
  otel-collector:
    image: otel/opentelemetry-collector:0.90.0
    restart: always
    command: ['--config=/etc/otel-collector-config.yaml', '']
    volumes:
      - ./docker/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - '4318:4318'
    depends_on:
      - jaeger